server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://45.77.10.213:3306/ywhl?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&multiStatementAllow=true
    username: root
    password: yang6218
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10